name: Deploy Quarto Site (GitHub Actions Pages)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11

      - name: Install Quarto CLI (local, no sudo)
        run: |
          set -euo pipefail
          if command -v quarto >/dev/null 2>&1; then
            echo "Quarto already installed: $(quarto --version)"
            exit 0
          fi
          # Try apt quickly (may not be available)
          if sudo apt-get update && sudo apt-get install -y quarto; then
            echo "Installed Quarto via apt"
            quarto --version
            exit 0
          fi
          URL="https://github.com/quarto-dev/quarto-cli/releases/download/v1.8.24/quarto-1.8.24-linux-amd64.tar.gz"
          echo "Downloading Quarto CLI from $URL"
          for i in 1 2 3; do
            curl -fsSL -o quarto.tar.gz "$URL" && break || (echo "download failed, retrying ($i)" && sleep 2)
          done
          mkdir -p "$RUNNER_TEMP/quarto-temp"
          tar -xzf quarto.tar.gz -C "$RUNNER_TEMP/quarto-temp"
          QUARTO_DIR=$(echo "$RUNNER_TEMP/quarto-temp"/* | awk '{print $1}')
          echo "Using extracted Quarto at: $QUARTO_DIR"
          echo "$QUARTO_DIR/bin" >> $GITHUB_PATH
          export PATH="$QUARTO_DIR/bin:$PATH"
          echo "Quarto path: $(ls "$QUARTO_DIR/bin")"
          "$QUARTO_DIR/bin/quarto" --version

      - name: Render Quarto site
        run: |
          quarto render

      - name: "Debug: show run info and site contents"
        run: |
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT"
          echo "Listing _site contents (if any):"
          ls -la _site || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

