name: Deploy Quarto Site (GitHub Actions Pages)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render Quarto site
        uses: quarto-dev/quarto-action@v2
        with:
          command: render

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
name: Deploy Quarto Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render Quarto site
        uses: quarto-dev/quarto-action@v2
        with:
          command: render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          publish_branch: gh-pages
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
