name: Deploy Quarto Site (GitHub Actions Pages)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11

      - name: Install Quarto via conda-forge
        run: |
          conda install -y -c conda-forge quarto

      - name: Install Quarto CLI
        run: |
          echo "Downloading Quarto CLI..."
          wget -qO quarto.tar.gz "https://github.com/quarto-dev/quarto-cli/releases/latest/download/quarto-linux-amd64.tar.gz"
          mkdir -p quarto-temp
          tar -xzf quarto.tar.gz -C quarto-temp
          sudo cp -r quarto-temp/*/bin/* /usr/local/bin/
          quarto --version

      - name: Render Quarto site
        run: |
          quarto render

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

