name: Deploy Quarto Site (GitHub Actions Pages)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11

      - name: Install Quarto via conda-forge
        run: |
          conda install -y -c conda-forge quarto

      - name: Install Quarto CLI (robust)
        run: |
          set -euo pipefail
          if command -v quarto >/dev/null 2>&1; then
            echo "Quarto already installed: $(quarto --version)"
            exit 0
          fi
          # Try apt (not likely to have latest but quick)
          if sudo apt-get update && sudo apt-get install -y quarto; then
            echo "Installed Quarto via apt"
            quarto --version
            exit 0
          fi
          # Download official tarball with retries
          URL="https://github.com/quarto-dev/quarto-cli/releases/latest/download/quarto-linux-amd64.tar.gz"
          echo "Downloading Quarto CLI from $URL"
          for i in 1 2 3; do
            curl -fsSL -o quarto.tar.gz "$URL" && break || echo "download failed, retrying ($i)" && sleep 2
          done
          mkdir -p quarto-temp
          tar -xzf quarto.tar.gz -C quarto-temp
          # Copy binaries to /usr/local/bin
          sudo cp -r quarto-temp/*/bin/* /usr/local/bin/
          chmod +x /usr/local/bin/quarto || true
          quarto --version

      - name: Render Quarto site
        run: |
          quarto render

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

