name: Run Notebooks

permissions:
  contents: write

on:
  push:
    paths:
      - 'notebooks/**'

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill nbconvert
          pip install -r requirements.txt || true
      - name: Execute notebook
        run: |
          mkdir -p _site/notebooks
          papermill notebooks/IntroductionImageProcessing.ipynb _site/notebooks/IntroductionImageProcessing.ipynb
          jupyter nbconvert --to html _site/notebooks/IntroductionImageProcessing.ipynb --output _site/notebooks/IntroductionImageProcessing.html
      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add _site/notebooks/IntroductionImageProcessing.html
            git commit -m "Auto-run notebook outputs"
            git push origin HEAD:main || echo "push failed"
          else
            echo "No changes to commit"
          fi
