name: Run Notebooks

permissions:
  contents: write

on:
  push:
    paths:
      - 'notebooks/**'

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill nbconvert
          pip install -r requirements.txt || true
      - name: Execute notebook
        run: |
          mkdir -p _site/notebooks
          papermill notebooks/IntroductionImageProcessing.ipynb _site/notebooks/IntroductionImageProcessing.ipynb
          jupyter nbconvert --to html _site/notebooks/IntroductionImageProcessing.ipynb --output _site/notebooks/IntroductionImageProcessing.html
      - name: Skip committing outputs (now handled by central deploy workflow)
        run: |
          echo "Notebook outputs will not be auto-committed by this workflow."
